### ISSUE TITLE
Could not run python bootstrap-buildout.py

### ISSUE THREAD

**Issue by tareqalam** [collective/tutorial-blog-angular2#15]
was giving me error like this:
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 178, in <module>
    ws.require(requirement)
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 966, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 852, in resolve
pkg_resources.DistributionNotFound: The 'zc.buildout==2.5.3' distribution was not found and is required by the application

**Comment by tareqalam** [comment]
To solve the issue I just had to:

``` python
virtualenv venv
cd venv
source bin/activate
cd tutorial-blog-angular2/backend
python bootstrap-buildout.py
```

then it worked!
